apiVersion: v1
kind: Secret
metadata:
  name: zoho-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zoho.labels" . | nindent 4}}
type: Opaque
data:
  zoho-token: {{ include "zoho.token" .  }}
---
