apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.image.pullSecrets }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zoho.labels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:
---
