apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      cpu: "100m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
    max:
      cpu: "150m"
      memory: "256Mi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
---
